In [1]:
import re
import nltk
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import os
import string

In [2]:
df = pd.read_csv('Reddit_Data.csv')
df

clean_comment  category
0       family mormon have never tried explain them t...         1
1      buddhism has very much lot compatible with chr...         1
2      seriously don say thing first all they won get...        -1
3      what you have learned yours and only yours wha...         0
4      for your own benefit you may want read living ...         1
...                                                  ...       ...
37244                                              jesus         0
37245  kya bhai pure saal chutiya banaya modi aur jab...         1
37246              downvote karna tha par upvote hogaya          0
37247                                         haha nice          1
37248             facebook itself now working bjp’ cell          0

[37249 rows x 2 columns]

In [4]:
nltk.download('stopwords')
 
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()

all_stopwords = stopwords.words('english')
all_stopwords.remove('not')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\nasit\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [39]:
x = []
for i in range(0,400):
    review = re.sub('[^a-zA-Z]', ' ', df['clean_comment'][i])
    review=review.lower()
    
    review=review.split()
    
    review=[ps.stem(word) for word in review if not word in set(all_stopwords)]
    review = ' '.join(review)
    x.append(review)

In [43]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train , y_test = train_test_split (x,y, test_size=0.2)

In [40]:
x

['famili mormon never tri explain still stare puzzl time time like kind strang creatur nonetheless come admir patienc calm equanim accept compass develop thing buddhism teach',
 'buddhism much lot compat christian especi consid sin suffer almost thing suffer caus want thing want go get thing wrong way christian would mean want thing coincid god want thing coincid without aid jesu buddhism could also seen proof god mighti omnipot certainli christian lucki one christ side everyon els well mani christian believ god grace salvat buddhism god way show grace upon other would also help studi thing jesu said see buddha made similar claim rich man get heaven joke basic advoc rid materi possess fact distinctli rememb jesu make someon cri someon ask achiev salvat jesu repli live like buddhist roughli translat also point buddha rare spoke anyth god theori person knew well enough leav jesu moham came later rememb conflict differ opinion educ fun involv enlighten easier teach someth prove right like

In [41]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features= 1000)

In [42]:
x = cv.fit_transform(x).toarray()
y = df.iloc[:400,-1].values

In [36]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 2],
       [0, 1, 0, ..., 0, 0, 0]], dtype=int64)

In [44]:
from sklearn.naive_bayes import GaussianNB
gb = GaussianNB()
gb.fit(x_train,y_train)

GaussianNB()

In [45]:
y_pred = gb.predict(x_test)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[ 6  0  9]
 [ 3 11  6]
 [ 5  5 35]]


0.65